### ISSUE TITLE
SCP URI pattern match  

### ISSUE THREAD

**Issue by volga629-1** [nat-418/scamp.nvim#5]
I am use SSH keys and no username in URI
On line 15 it through the error.

'''
scp://dev//etc/myfile.cfg

'''

**Comment by nat-418** [comment]
I have pushed a fix to the `main` branch. Please test and let me know if this fixes your bug.

**Comment by volga629-1** [comment]
Thank you for pushing fix, plugin works good right now 

That good output.

```
Error: failed to edit scp://dev-rtp-1/etc/app/app.cfg
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
scp: Connection closed
```
